@startuml LabResults

activate "Lab System"
"Lab System" -> "Lab System": Receives order
deactivate "Lab System"

activate "Lab Technician"
"Lab Technician" -> "Lab System": Gets order
"Lab Technician" -> "Lab Device": Initiates testing
deactivate "Lab Technician"

activate "Lab Device"
"Lab Device" -> "Lab Device": Execute test
"Lab Device" --> "Lab Technician": Result data
deactivate "Lab Device"

activate "Lab Technician"
"Lab Technician" --> "Lab System": Capture result data
deactivate "Lab Technician"

activate "Lab System"
"Lab System" -> "Lab System": Generate diagnostic report
"Lab System" -> "EMR": Submit diagnostic report
deactivate "Lab System"

@enduml